#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "teampass"
name = "Teampass"
description.en = "Passwords Manager"
description.fr = "Gestionnaire de mots de passes"

version = "3.1.1~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
website = "http://www.teampass.net"
admindoc = "https://teampass.readthedocs.io/en/latest/"
code = "https://github.com/nilsteampassnet/TeamPass"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/teampass"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://github.com/nilsteampassnet/TeamPass/archive/refs/tags/3.1.1.tar.gz"
    sha256 = "c4d1dd4a094e211fd4aeaac0cacb14441836294007d1308b71f9823ecd499d3e"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "mariadb-server",
        "php8.2-mbstring",
        "php8.2-bcmath",
        "php8.2-iconv",
        "php8.2-xml",
        "php8.2-gd",
        "php8.2-curl",
        "php8.2-mysqli",
        "php8.2-gmp",
        "php8.2-mcrypt",
        "openssl",
        "python3-bcrypt",
    ]

    [resources.database]
    type = "mysql"

