packaging_format = 2

id = "teampass"
name = "Teampass"
description.en = "Passwords Manager"
description.fr = "Gestionnaire de mots de passes."

version = "3.0.0.23~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
website = "http://www.teampass.net"
admindoc = "https://teampass.readthedocs.io/en/latest/"
code = "https://github.com/nilsteampassnet/TeamPass"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/teampass"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/nilsteampassnet/TeamPass/archive/refs/tags/3.0.0.23.tar.gz"
        sha256 = "b010d1ea2cf0ace9fbeef30b448e864e3bc767f9f6e5beac79f0bf7e359005e7"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php7.4-mbstring php7.4-bcmath php7.4-iconv php7.4-xml php7.4-gd php7.4-curl php7.4-mysqli"


    [resources.database]
    type = "mysql"
