#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.a911e5089713308fff04d85828c7ad69612b3fb0.name = "Upgrade from 2.1.27.15"
