#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.499353641d5e039f19c2f519618690630c8c4a16.name = "Upgrade from 3.0.0.23"
