#!/bin/bash

user=$1
root_pwd=$(sudo cat /etc/yunohost/mysql)
db_user=root
db_name=teampass
real_password=$(ynh_string_random)	# Génère un mot de passe aléatoire
password=$(sudo php /var/www/teampass/mdphash.php $real_password)


mail=$(sudo ldapsearch -h localhost -b ou=users,dc=yunohost,dc=org -x uid=$user mail | grep mail: | sed 's/mail: //' | head -n1)

# Creation de l'utilisateur
mysql -u $db_user -p$root_pwd $db_name -e "INSERT INTO teampass_users (id, login, pw, groupes_visibles, derniers, key_tempo, last_pw_change, last_pw, admin, fonction_id, groupes_interdits, last_connexion, gestionnaire, email, favourites, latest_items, personal_folder, can_create_root_folder) VALUES (NULL, '$user', '$password', '1', '', '', '', '', '0', '1', '', '', '0', '$mail', '', '', '1', '1');"
# Creation du répertoire personnel
id=$(mysql -u $db_user -p$root_pwd $db_name -se "SELECT id from teampass_users where login='$user';")
mysql -u $db_user -p$root_pwd $db_name -e "INSERT INTO teampass_nested_tree (id, parent_id, title, nleft, nright, nlevel, bloquer_creation, bloquer_modification, personal_folder, renewal_period) VALUES (NULL, 0, '$id', 0, 0, 1, 0, 0, 1, 0);"
