#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

old_domain=$YNH_APP_OLD_DOMAIN
old_path=$YNH_APP_OLD_PATH

new_domain=$YNH_APP_NEW_DOMAIN
new_path=$YNH_APP_NEW_PATH

app=$YNH_APP_INSTANCE_NAME

#=================================================
# LOAD SETTINGS
#=================================================

final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# CHECK THE SYNTAX OF THE PATHS
#=================================================

test -n "$old_path" || old_path="/"
test -n "$new_path" || new_path="/"
new_path=$(ynh_normalize_url_path $new_path)
old_path=$(ynh_normalize_url_path $old_path)

#=================================================
# ACTIVATE MAINTENANCE MODE
#=================================================

path_url=$old_path
domain=$old_domain
ynh_maintenance_mode_ON

#=================================================
# CHECK WHICH PARTS SHOULD BE CHANGED
#=================================================

change_domain=0
if [ "$old_domain" != "$new_domain" ]
then
	change_domain=1
fi

change_path=0
if [ "$old_path" != "$new_path" ]
then
	change_path=1
fi

#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# MODIFY URL IN NGINX CONF
#=================================================

nginx_conf_path=/etc/nginx/conf.d/$old_domain.d/$app.conf

# Change the path in the nginx config file
if [ $change_path -eq 1 ]
then
	# Make a backup of the original nginx config file if modified
	ynh_backup_if_checksum_is_different "$nginx_conf_path"

	# Move from sub path to root
	if [ "$new_path" == "/" ]
	then
		ynh_replace_string "^.*rewrite.*\^$old_path" "#sub_path_only&" "$nginx_conf_path"

		ynh_replace_string "\(rewrite *\^\)$old_path\$ $old_path/*" "\1$new_path$ $new_path" "$nginx_conf_path"

	# Move to a sub path
	else
		ynh_replace_string "^#sub_path_only" "" "$nginx_conf_path"
		ynh_replace_string "\(rewrite *\^\)$old_path\$ $old_path/*" "\1$new_path$ $new_path/" "$nginx_conf_path"
	fi

	ynh_replace_string "location ${old_path%/}/" "location ${new_path%/}/" "$nginx_conf_path"

	# Calculate and store the nginx config file checksum
	ynh_store_file_checksum "$nginx_conf_path"
fi

# Change the domain for nginx
if [ $change_domain -eq 1 ]
then
	# Delete file checksum for the old conf file location
	ynh_delete_file_checksum "$nginx_conf_path"
	mv $nginx_conf_path /etc/nginx/conf.d/$new_domain.d/$app.conf

	nginx_conf_path=/etc/nginx/conf.d/$new_domain.d/$app.conf
	# Calculate and store the nginx config file checksum
	ynh_store_file_checksum "$nginx_conf_path"
fi

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# UPDATE THE DATABASE
#=================================================

ynh_mysql_execute_as_root "UPDATE ${app}_misc SET valeur='https://$new_domain$new_path' WHERE intitule='cpassman_url'" $app
ynh_mysql_execute_as_root "UPDATE ${app}_misc SET valeur='https://$new_domain$new_path/favico.ico' WHERE intitule='favicon'" $app
ynh_mysql_execute_as_root "UPDATE ${app}_misc SET valeur='https://$new_domain$new_path/upload' WHERE intitule='url_to_upload_folder'" $app
ynh_mysql_execute_as_root "UPDATE ${app}_misc SET valeur='https://$new_domain$new_path/files' WHERE intitule='url_to_files_folder'" $app
ynh_mysql_execute_as_root "UPDATE ${app}_misc SET valeur='https://$new_domain$new_path' WHERE intitule='email_server_url'" $app

#=================================================
# UPDATE TP.CONFIG.PHP FILE
#=================================================

ynh_replace_string "https://$old_domain$old_path" "https://$new_domain$new_path" "$final_path/includes/config/tp.config.php"

#=================================================
# GENERIC FINALISATION
#=================================================
# RELOAD NGINX
#=================================================

ynh_system_reload nginx

#=================================================
# DEACTIVE MAINTENANCE MODE
#=================================================

path_url=$old_path
domain=$old_domain
ynh_maintenance_mode_OFF
