#!/bin/bash
app=teampass

# Retrieve arguments
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)

# Remove sources
sudo rm -rf /var/www/$app

# Remove configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

db_user=teampass
db_name=teampass
mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
