#!/bin/bash

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

# Récupère les infos de l'application.
app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

domain=$(ynh_app_setting_get $app domain)

REMOVE_BDD $app	# Suppression de la base de donnée et de l'utilisateur associé.

SECURE_REMOVE '/var/www/$app'	# Suppression du dossier de l'application

# Remove the sk.php
if [ -e "/etc/teampass/" ]; then
	echo "Delete sk.php"
	sudo rm -r "/etc/teampass/"
fi

REMOVE_NGINX_CONF	# Suppression de la configuration nginx

SECURE_REMOVE '/var/log/$app/'	# Suppression des log

REMOVE_FPM_CONF	# Suppression de la configuration du pool php-fpm

REMOVE_SYS_USER	# Supprime l'user système dédié pour l'application

# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf

echo -e "\e[0m"	# Restore normal color
