#!/bin/bash

# Récupère les infos de l'application.
app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

domain=$(ynh_app_setting_get $app domain)
final_path=$(ynh_app_setting_get $app final_path)

# The parameter $1 is the uncompressed restore directory location
backup_dir=$1/apps/$app

# Restore Nginx
conf=/etc/nginx/conf.d/$domain.d/$app.conf
if [ -f $conf ]; then
    echo "There is already a nginx conf file at this path: $conf " >&2
    ynh_die
fi
sudo cp -a $backup_dir/nginx.conf $conf

# Restore YunoHost parameters
sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app

# Restore sources & data
sudo cp -a "$backup_dir/sources/." $final_path

# Créer la base de donnée et la restaure
db_pwd=$(ynh_app_setting_get $app mysqlpwd)
db_user=$app
ynh_mysql_create_db $db_user $db_user $db_pwd
mysql --debug-check -u $db_user -p$db_pwd $db_user < ${backup_dir}/db.sql

# Copy dedicated php-fpm process from backup folder to the right location
sudo cp -a $backup_dir/php-fpm.conf /etc/php5/fpm/pool.d/$app.conf
sudo cp -a $backup_dir/php-fpm.ini /etc/php5/fpm/conf.d/20-$app.ini

# ADD_SYS_USER	# Créer un user système dédié pour l'application
if ! ynh_system_user_exists "$app"	# Test l'existence de l'utilisateur
then
	sudo useradd -d /var/www/$app --system --user-group $app --shell /usr/sbin/nologin || (echo "Unable to create $app system account" >&2 && false)
fi

# Copie du fichier sk.php
sudo mkdir /etc/teampass
sudo cp -a $backup_dir/sk.php /etc/teampass/sk.php
sudo chown -R root:$app /etc/teampass/sk.php

# Les fichiers appartiennent à root
sudo chown -R root:$app $final_path

# And Reload service
sudo service php5-fpm reload

# Reload webserver
sudo service nginx reload
